/// <reference path="sst-env.d.ts" />

import 'sst'

/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module 'sst' {
  export interface Resource {}
}

export {}
