import './globals.css'

import type { Metadata } from 'next'
import type { PropsWithChildren } from 'react'

import { ThemeProvider } from 'next-themes'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <ThemeProvider attribute='class' disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
